// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact         = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUiFileInput = require("material-ui-file-input");

function make($staropt$star, label, onChange, $staropt$star$1, formControlProps, inputLabelProps, inputProps, _) {
  var name = $staropt$star ? $staropt$star[0] : "";
  var helperText = $staropt$star$1 ? $staropt$star$1[0] : "";
  return ReasonReact.wrapJsForReason(MaterialUiFileInput.default, {
              name: name,
              label: label,
              onChange: onChange,
              helperText: helperText,
              formControlProps: formControlProps,
              inputLabelProps: inputLabelProps,
              inputProps: inputProps
            }, /* array */[]);
}

exports.make = make;
/* ReasonReact Not a pure module */
